name: croma_brokrage
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your p ackage needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  get: any
  fluttertoast:  ^8.0.7
  connectivity: ^3.0.6
  flutter_local_notifications: ^9.7.0
  url_launcher: ^6.0.3
  flutter_slider_drawer: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  #google_fonts: ^2.1.0
  #tuple: ^1.0.3
  #encrypt: any
  local_auth: any
  #polygon_clipper: ^1.0.2
  #tinycolor: ^1.0.3
  badges: ^2.0.1
  convex_bottom_bar: ^3.0.0
  flutter_statusbarcolor_ns: ^0.4.0
  bottom_navy_bar: any
  keyboard_actions: ^4.0.1
  package_info: any
  plugin_platform_interface: ^2.0.1
  http: ^0.13.0
  #shared_preferences_linux: ^2.0.0
  #shared_preferences_platform_interface: ^2.0.0
  #shared_preferences_windows: ^2.0.0
  pattern_lock: ^2.0.0
  clay_containers: ^0.3.2
  connectivity_platform_interface: ^2.0.1
  #flutter_local_notifications_platform_interface: ^4.0.0
  path_provider: ^2.0.2
  #path_provider_linux: ^2.0.0
  #path_provider_windows: ^2.0.1
  #qr_flutter: ^4.0.0
  #share_extend: ^2.0.0
  #basic_utils: ^3.3.3
  #http_parser: ^4.0.0
  #path_provider_platform_interface: ^2.0.1
  #xdg_directories: ^0.2.0
  font_awesome_flutter: ^10.1.0
  page_transition: ^2.0.2
  #tmpl : ^1.0.0
  #intl : ^0.16.1
  salomon_bottom_bar: ^3.3.0
  slide_countdown_clock: ^1.0.3
  flip_card: ^0.6.0
  flutter_icons: ^1.1.0
  carousel_slider: ^4.0.0
  sms_autofill: ^2.2.0
  pin_code_fields: ^7.4.0
  multi_select_item: ^1.0.3
  google_maps_flutter: ^2.1.7
  flutter_tab_indicator_styler: ^2.0.0
  lottie: ^1.3.0
  admob_flutter: ^3.0.0
  firebase: any
  firebase_admob: any
  syncfusion_flutter_sliders: ^20.1.59
  image_picker: ^0.8.5+3
  web_socket_channel: ^2.2.0
  animated_text: ^1.0.2
  intl: ^0.17.0
  modal_bottom_sheet: ^2.1.0
  flutter_datetime_picker: ^1.5.1
  contacts_service: ^0.6.3
  permission_handler: ^10.0.0
  sms_otp_auto_verify: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/logo/ic_main_logo.png"
  android: true
  ios: true

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/background/
    - assets/icon/
    - assets/flags/
    - assets/logo/
    - assets/lottie_json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages